exp_name: my_experiment 
train:
  train_inp:  # <path to the directory of blur input images for training>
  train_dep: # <path to the directory of depth input images for training>
  valid_inp: # <path to the directory of blur input images for validation>
  valid_gt:   # <path to the directory of rgb ground truth images for validation>
  valid_dep:  # <path to the directory of depth input images for validation>
  batch_size: 8
  patch_size: 256
  epoch: 5
  lr: 1e-4
  num_workers: 0
  save_every: 10 # frequency of save the model
  prompt_tuning: false #if you want to freeze all the network and only training the adapter, set to true
  encoder_freezing: false # if you wan to freeze all the encoder,

test:
  test_inp:  # <path to the directory of blur input images for test>
  test_gt:  # <path to the directory of rgb ground truth images for test>
  test_dep:  # <path to the directory of depth input images for validation>
  num_workers: 0
  save: false #if you need save the image


model:
  name: CatRestormer
  setting: false
  pretrained: /home/valsesia/Scripts/restoration-optimized-compression/pretrained/orig/catrestormer_licam.tar  # checkpoint location set false if is none
  gpu_ids: false
  num_gpus: 1  ### while test or demo please set num_gpu to 1
  node: 0
  resume: false # toggle this if issues with importing model
  #resume: true 
  testing_from_dp: False 
