model: "tic_promptmodel_MS_encdec"
dataset: ""
dataset_path: "/home/valsesia/Scripts/restoration-optimized-compression/data/LICAM/pretrain/blur"
depth_train: "/home/valsesia/Scripts/restoration-optimized-compression/data/LICAM/pretrain/depth"
gt_train: "/home/valsesia/Scripts/restoration-optimized-compression/data/LICAM/pretrain/sharp"
kodak_path: "/home/valsesia/Scripts/restoration-optimized-compression/data/LICAM/test/blur"
depth_test: "/home/valsesia/Scripts/restoration-optimized-compression/data/LICAM/test/depth"
gt_test: "/home/valsesia/Scripts/restoration-optimized-compression/data/LICAM/test/sharp"
input_resolution: 256
epochs: 30
learning_rate: 1.e-5
num_workers: 4
quality_level: 4
batch_size: 2 # x4 due to accumulation in code
test_batch_size: 1
aux_learning_rate: 1.e-4
patch_size: 256
cuda: True
gpu_id: 2
save: True
clip_max_norm: 1.0
name: "JOINT_FINETUNE_LICAM"
exp_name: "JOINT_FINETUNE_LICAM"
seed: 42
root: "/home/valsesia/Scripts/restoration-optimized-compression/"
checkpoint: "/home/valsesia/Scripts/restoration-optimized-compression/pretrained/orig/compressor.pth.tar"
LOCATION: 'prepend'
DEEP: True
NUM_TOKENS: 16
INITIATION: 'random'
PROJECT: -1
DROPOUT: 0.
TRANSFER_TYPE: 'prompt'
ARCHITECT: 'both'
WINDOW: 'same' 
RETURN_ATTENTION: False
MASK_DOWNSAMPLE: 2
TEST: False
lambda_mul_debug: 1.0
