model: "tic_promptmodel_MS_encdec"
dataset: ""
dataset_path: "/home/valsesia/Scripts/restoration-optimized-compression/data/ArkitScenes/Training/wide_resized"
depth_train: "/home/valsesia/Scripts/restoration-optimized-compression/data/ArkitScenes/Training/lowres_depth_resized"
kodak_path: "/home/valsesia/Scripts/restoration-optimized-compression/data/ArkitScenes/Validation/wide1"
depth_test: "/home/valsesia/Scripts/restoration-optimized-compression/data/ArkitScenes/Validation/lowres_depth_resized1"
input_resolution: 256
epochs: 50
learning_rate: 1.e-4
num_workers: 4
quality_level: 4
batch_size: 8
test_batch_size: 1
aux_learning_rate: 1.e-3
patch_size: 256
cuda: True
gpu_id: 7
save: True
clip_max_norm: 1.0
name: "PRETRAIN_COMPRESSOR_AR"
exp_name: "PRETRAIN_COMPRESSOR_AR"
seed: 42
root: "/home/valsesia/Scripts/restoration-optimized-compression/"
checkpoint: ""
LOCATION: 'prepend'
DEEP: True
NUM_TOKENS: 16
INITIATION: 'random'
PROJECT: -1
DROPOUT: 0.
TRANSFER_TYPE: 'prompt'
ARCHITECT: 'both'
WINDOW: 'same' 
RETURN_ATTENTION: False
MASK_DOWNSAMPLE: 2
TEST: False
